name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run report

      - name: Generate HTML report
        run: |
          npm install multiple-cucumber-html-reporter --save-dev
          node cucumber-html-report.js --report-dir cypress/reports/cucumber/index.html
          
      - name: Publish reports as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/reports/cucumber/index.html
